### ISSUE TITLE
[Feature Request] Make ALERT_KEY configurable

### ISSUE THREAD

**Issue by mcwqy9** [airbnb/interferon#37]
I'm happy to take a stab at this, but would like to collaborate on how to implement before doing so. Here's what I'm thinking:
1) Add an alert_key like to the config.yml file passed to interferon, like so:
```
destinations:
  - type: datadog
    enabled: true
    options:
      alert_key: "My custom alert key"
```
2) Define a new instance method `Interferon::Destinations::Datadog#alert_key` that prefers the value from the config, but falls back to a constant default.

3) In lib/interferon/destinations/datadog.rb, turn `Interferon::Destinations::Datadog.generate_message` into an instance method, so it can access the `alert_key` instance method. Same for self.same_alerts, turn it into an instance method. As near as I can tell  `same_alerts` and `generate_message` are only ever called by instance methods anyway?

Thoughts?
